# Hadolint configuration file
# Documentation: https://github.com/hadolint/hadolint

# Ignore specific rules
ignored:
  - DL3008  # Pin versions in apt-get install
  - DL3013  # Pin versions in pip install
  - DL3018  # Pin versions in apk add
  - DL3019  # Use the --no-cache flag with apk add
  - DL3020  # Use COPY instead of ADD for files and folders
  - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT arguments
  - DL3059  # Multiple consecutive RUN instructions
  - DL4000  # MAINTAINER is deprecated
  - SC2086   # Double quote to prevent globbing and word splitting
  - SC2155   # Declare and assign separately to avoid masking return values

# Set the failure threshold (can be: error, warning, info, style, ignore)
failure-threshold: warning

# Output format (can be: tty, json, codeclimate, gitlab_codeclimate, checkstyle, codacy, json, tty, gnu, gitlab_sast)
format: tty

# No color output
no-color: false

# Don't fail on ignored rules
no-fail: false

# Verbose output
verbose: true

# Trust all registries
trusted-registries:
  - docker.io
  - ghcr.io
  - gcr.io
  - public.ecr.aws
  - quay.io

# Allow specific registries
allowed-registries:
  - docker.io
  - ghcr.io
  - gcr.io
  - public.ecr.aws
  - quay.io

# Allow specific registries for FROM instructions
allowed-from:
  - docker.io/library/*
  - ghcr.io/*
  - gcr.io/*
  - public.ecr.aws/*
  - quay.io/*

# Allow specific registries for COPY --from
allowed-copy-from:
  - docker.io/library/*
  - ghcr.io/*
  - gcr.io/*
  - public.ecr.aws/*
  - quay.io/*

# Allow specific registries for RUN --mount=type=secret
allowed-secret-mounts:
  - docker.io/library/*
  - ghcr.io/*
  - gcr.io/*
  - public.ecr.aws/*
  - quay.io/*

# Allow specific registries for RUN --mount=type=ssh
allowed-ssh-mounts:
  - docker.io/library/*
  - ghcr.io/*
  - gcr.io/*
  - public.ecr.aws/*
  - quay.io/*

# Allow specific registries for RUN --mount=type=cache
allowed-cache-mounts:
  - docker.io/library/*
  - ghcr.io/*
  - gcr.io/*
  - public.ecr.aws/*
  - quay.io/*

# Allow specific registries for RUN --mount=type=bind
allowed-bind-mounts:
  - docker.io/library/*
  - ghcr.io/*
  - gcr.io/*
  - public.ecr.aws/*
  - quay.io/*

# Allow specific registries for RUN --mount=type=tmpfs
allowed-tmpfs-mounts:
  - docker.io/library/*
  - ghcr.io/*
  - gcr.io/*
  - public.ecr.aws/*
  - quay.io/*
