repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
        args: [--pdb]
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py39]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --line-length=88, --filter-files]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.2.6
          - flake8-comprehensions==3.14.0
          - flake8-docstrings==1.7.0
          - flake8-rst-docstrings==0.3.0
          - flake8-annotations==3.1.0
          - flake8-import-order==0.18.2
          - flake8-typing-imports==1.15.0
        args:
          - --max-line-length=88
          - --ignore=E203,W503
          - --max-complexity=18
          - --select=B,C,E,F,W,T4,B9
          - --extend-select=B950
          - --per-file-ignores=__init__.py:F401

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML>=6.0.0
          - types-requests>=2.31.0
          - types-python-dateutil>=2.8.0
          - types-pytz>=2023.3
          - types-setuptools>=68.0.0
        args:
          - --strict
          - --ignore-missing-imports
          - --implicit-optional
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --warn-return-any
          - --warn-unreachable
          - --strict-equality
          - --python-version=3.9

  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        name: pylint (python)
        entry: pylint
        language: system
        types: [python]
        args:
          - --rcfile=pyproject.toml
          - --output-format=colorized
          - --score=no
        additional_dependencies:
          - pylint-pytest>=1.1.2
          - pylint-plugin-utils>=0.8.2

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --target-version=py39]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
        args: [--retry, '1', '--retry, 3']

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject
        additional_dependencies: [validate-pyproject[all]~=0.16]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown, html, css, scss, javascript, typescript, typescriptreact, json, jsonc]
        args: [--prose-wrap=always, --print-width=88, --tab-width=4, --no-semi, --single-quote]
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-sort-json@3.2.0
          - prettier-plugin-toml@0.3.2
          - prettier-plugin-packagejson@2.4.5
          - @prettier/plugin-xml@3.1.0
          - @prettier/plugin-yaml@3.2.4

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-pyyaml]
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        exclude: ^tests/
