version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    
  json:
    (): evoseal.utils.logging.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
    filters: [context_filter]

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/evoseal.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
    filters: [context_filter]
    
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
    filters: [context_filter]
    
  performance:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
    filters: [performance_filter]

filters:
  context_filter:
    (): evoseal.utils.logging.ContextFilter
  performance_filter:
    (): evoseal.utils.logging.PerformanceFilter

loggers:
  evoseal:
    level: DEBUG
    handlers: [console, file, error_file, performance]
    propagate: False
    
  evoseal.performance:
    level: INFO
    handlers: [performance]
    propagate: False
    
  evoseal.requests:
    level: INFO
    handlers: [file, console]
    propagate: False

root:
  level: WARNING
  handlers: [console]
