name: "Snyk Security Scan"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight

jobs:
  security:
    name: Run Snyk security scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full git history for Snyk
      
      - name: Debug repository contents
        run: |
          ls -la
          if [ -f requirements.txt ]; then
            echo "requirements.txt found. Contents:"
            cat requirements.txt
          else
            echo "No requirements.txt found"
          fi
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then 
            echo "Installing requirements..."
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, installing project in development mode..."
            pip install -e .
          fi
          echo "Installing Snyk..."
          npm install -g snyk
          snyk --version
          
      - name: Run Snyk to check for vulnerabilities
        id: snyk-test
        continue-on-error: true
        run: |
          if [ -z "$SNYK_TOKEN" ]; then
            echo "SNYK_TOKEN is not set. Please add it to your GitHub secrets."
            exit 1
          fi
          snyk auth $SNYK_TOKEN
          # Create a directory for the SARIF file
          mkdir -p .github/snyk
          # Run Snyk test and output to the SARIF file
          snyk test --severity-threshold=high --sarif-file-output=.github/snyk/snyk.sarif || echo "Snyk test found vulnerabilities"
          # Check if the file was created
          if [ -f ".github/snyk/snyk.sarif" ]; then
            echo "SARIF file created successfully"
          else
            echo "Warning: SARIF file was not created"
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .github/snyk/snyk.sarif
          
      - name: Snyk Monitor
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.snyk-test.outcome == 'success'
        run: |
          snyk monitor --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
